snd-soc-sst-haswell-pcm-objs := \
	        sst-haswell-ipc.o sst-haswell-pcm.o
snd-soc-sst-haswell-dsp-objs := \
		sst-haswell-dsp.o

obj-$(CONFIG_SND_SOC_INTEL_HASWELL) += snd-soc-sst-haswell-pcm.o
obj-$(CONFIG_SND_SOC_INTEL_HASWELL_DSP) += snd-soc-sst-haswell-dsp.o
