snd-soc-sst-baytrail-pcm-objs := \
	        sst-baytrail-ipc.o sst-baytrail-pcm.o
snd-soc-sst-baytrail-dsp-objs := \
		sst-baytrail-dsp.o

obj-$(CONFIG_SND_SOC_INTEL_BAYTRAIL) += snd-soc-sst-baytrail-pcm.o
obj-$(CONFIG_SND_SOC_INTEL_BAYTRAIL_DSP) += snd-soc-sst-baytrail-dsp.o
